travis:
  secure:
    BINSTAR_TOKEN: J8dyfoOIA4G/Jb9hQ+AD4ugQJs9ttSg90UKyQU/uVOVZ3qfmSLyGNzwW9goeaHqqzXEsXOQyZMkZewZlv6IzJb47C5QtmLJPPNgYHfY3VbLGWFXJc3Pdb7GYlrEE+lwIpYE8fLY8fmTmLoC7t/QMGiJvkrPo0awXZ40SWSJV/mc4pgMFIZYd9Czm1PWVjRMQBM8tWyf/DnKSi3JAmIHgW12L2M/cq/KyO7VnopN5Lb58hg0W5EUu2mwW7OtzV9HDu+seyTRaZgQYnPYzyUyKb6fQZF9oAttJ1tT8OSU/iGZdl+YYElvsTfA2A0JoJLNiK7HFA2VcLT2WmWXLcmdgztdNSHVPSOZzjco15yvq7dgBHJFZNlJBsragG1fpTarpPGyf0GmCsifL71FoTPOBVexvtJn7Ly7apBS717Tdm28AHro4nVvWlsNgN9Tak5SZxP+yv+22hw6n1N+b7gWecz5AYwmmVXOKzZdoIBoPuxjsavgz+nWBZtzHFb7QkT7oAqugglMOn4OWIFjFOXcdN44jvYHnen6+OB3uQbsrxWM5E1jchUVfwS4sK/pUckbVLwqFqSoEenCvAO1l1l/ibTozROSaIMtJnnFwyyn1M9t8iV/0z9SnBqwezYM9/eN7FBWvOW2LPR46novSlYmoywZew8oqsTRD301xab+sKFg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
